import {
  Gauge,
  Radar,
  Table2,
  Stethoscope,
  Target,
  LayoutTemplate,
  Send,
  Columns3,
  ChartNoAxesColumn,
  Cpu,
  Settings2,
  Ellipsis,
  Plug,
  MessageCircle,
  AtSign,
  Mail,
  Contact,
  Rocket,
  Database,
  Search,
  Building2,
  Globe,
  Users,
  Phone,
  Wallet,
  ShieldCheck,
  KeyRound,
  Sparkles,
  FileText,
  GitBranch,
  HardDrive,
  BadgeCheck,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  gauge: Gauge,
  radar: Radar,
  table: Table2,
  stethoscope: Stethoscope,
  target: Target,
  layout: LayoutTemplate,
  send: Send,
  columns: Columns3,
  chart: ChartNoAxesColumn,
  cpu: Cpu,
  settings: Settings2,
  more: Ellipsis,
  plug: Plug,
  whatsapp: MessageCircle,
  instagram: AtSign,
  email: Mail,
  linkedin: Contact,
  deploy: Rocket,
  database: Database,
  search: Search,
  business: Building2,
  globe: Globe,
  facebook: Users,
  phone: Phone,
  wallet: Wallet,
  shield: ShieldCheck,
  key: KeyRound,
  sparkles: Sparkles,
  doc: FileText,
  branch: GitBranch,
  storage: HardDrive,
  check: BadgeCheck,
};

export function NavIcon({ name, className }: { name: string; className?: string }) {
  const Cmp = MAP[name] ?? Gauge;
  return <Cmp className={className} strokeWidth={1.75} aria-hidden />;
}
