import { BUILD_QUALITY, STRATEGY_META, type BuildQuality, type BuildStrategy } from "@/config/build";
import { prisma } from "@/db/client";
import { AppError } from "@/lib/errors";
import { fromJson } from "@/lib/json";
import { sha256 } from "@/lib/crypto";
import { createZip, safeFilename, type ZipEntry } from "@/lib/zip";
import { getStorageProvider } from "@/providers/storage";
import type { QualityReport, WebsiteBrief } from "@/types";

/**
 * Packaging a build into something a human can actually use.
 *
 * Three jobs, in order:
 *   1. persist every file as a WebsiteArtifact row, so the build survives the
 *      machine that produced it;
 *   2. write a README that tells the truth about how the site was made, what
 *      was verified and what still needs a person;
 *   3. hand back a ZIP on request.
 *
 * The README is the honest part. It names the model, records what the quality
 * gate could not check, and lists every fact the generator was not given —
 * because a site that quietly invents an address is worse than one that says
 * `[CLIENT TO CONFIRM]`.
 */

export type PackagedFile = { path: string; content: string };

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json",
  ".svg": "image/svg+xml",
  ".xml": "application/xml",
  ".txt": "text/plain; charset=utf-8",
  ".md": "text/markdown; charset=utf-8",
};

export function contentTypeFor(path: string): string {
  const ext = path.slice(path.lastIndexOf(".")).toLowerCase();
  return CONTENT_TYPES[ext] ?? "application/octet-stream";
}

/* ------------------------------------------------------------------ README */

export type ReadmeInput = {
  businessName: string;
  city: string | null;
  slug: string;
  version: number;
  brief: WebsiteBrief | null;
  report: QualityReport | null;
  strategy: BuildStrategy;
  requestedStrategy: BuildStrategy;
  fallbackReason: string | null;
  quality: BuildQuality;
  provider: string;
  model: string;
  iterations: number;
  files: PackagedFile[];
  builtAt: Date;
  auditUrl: string | null;
  visualQaAvailable: boolean;
};

export function renderReadme(input: ReadmeInput): string {
  const skipped = (input.report?.checks ?? []).filter((c) => c.status === "skipped");
  const failed = (input.report?.checks ?? []).filter((c) => c.status === "fail");
  const unknowns = input.brief?.requiresClientInput ?? [];

  const lines: string[] = [];
  const h = (text: string) => lines.push(`\n## ${text}\n`);

  lines.push(`# ${input.businessName} — website`);
  lines.push("");
  lines.push(
    `A static marketing site generated by Lead → Launch for ${input.businessName}${
      input.city ? `, ${input.city}` : ""
    }. This is **version ${input.version}**, built on ${input.builtAt.toISOString().slice(0, 10)}.`,
  );

  h("What this is");
  lines.push(
    "Plain HTML and CSS with no build step and no external requests. Open `index.html` in a browser and it works; there is nothing to install to view it.",
  );

  h("Running it locally");
  lines.push("```bash");
  lines.push("# Any static server will do. With Node installed:");
  lines.push("npx serve .");
  lines.push("");
  lines.push("# Or with Python:");
  lines.push("python -m http.server 8000");
  lines.push("```");
  lines.push("");
  lines.push("Then open <http://localhost:8000>.");

  h("Build commands");
  lines.push(
    "There are none. This is deliberately a no-build site: no bundler, no package manager, no lockfile to go stale. Edit the HTML and CSS directly.",
  );

  h("Environment variables");
  lines.push(
    "None. Nothing here reads configuration, calls an API or stores data. If you add a contact form, whatever backend you point it at is the first thing that will need one.",
  );

  h("Deploying it");
  lines.push(
    "Upload the contents of this folder to any static host — Netlify drop, Vercel, Cloudflare Pages, S3 + CloudFront, or plain nginx. There is no server-side component.",
  );
  lines.push("");
  lines.push(
    "**This site was not deployed by Lead → Launch.** Deployment is a deliberate manual step taken after a human has reviewed the result.",
  );

  h("How it was generated");
  lines.push(`- **Strategy:** ${STRATEGY_META[input.strategy].label}`);
  lines.push(`- **Provider / model:** ${input.provider} / ${input.model}`);
  lines.push(
    `- **Quality mode:** ${BUILD_QUALITY[input.quality].label} — ${BUILD_QUALITY[input.quality].summary}`,
  );
  lines.push(`- **Iterations run:** ${input.iterations}`);
  lines.push(`- **Files:** ${input.files.length}`);
  if (input.fallbackReason) {
    lines.push("");
    lines.push(
      `> **The build did not run the way it was requested.** ${STRATEGY_META[input.requestedStrategy].label} was asked for, but ${input.fallbackReason} The ${STRATEGY_META[input.strategy].label.toLowerCase()} produced this site instead.`,
    );
  }
  if (input.strategy === "scaffold") {
    lines.push("");
    lines.push(
      "> This version was assembled deterministically from the business record. No language model wrote any of it, and nothing in it was inferred — which also means it will not read better than its template.",
    );
  }

  h("Where the business facts came from");
  lines.push(
    "Every name, address, phone number, service and opening time on this site came from the business record in Lead → Launch, which was populated by the discovery provider and the website audit. Nothing was invented to fill a gap.",
  );
  if (input.auditUrl) lines.push(`\nThe audit that informed the copy was run against ${input.auditUrl}.`);

  h("Content requiring client confirmation");
  if (unknowns.length === 0) {
    lines.push(
      "The brief recorded no outstanding unknowns. Still read the copy before it goes live — a fact being *present* is not the same as it being *current*.",
    );
  } else {
    lines.push(
      "These were not available when the site was generated. Search the source for `[CLIENT TO CONFIRM]` — each one is marked in place rather than guessed:",
    );
    lines.push("");
    for (const u of unknowns) lines.push(`- [ ] ${u}`);
  }

  h("What was checked, and what was not");
  if (input.report) {
    lines.push(`Automated quality gate: **${input.report.score}/100**.`);
    lines.push("");
    if (failed.length) {
      lines.push("Failing checks, carried into this version rather than hidden:");
      lines.push("");
      for (const c of failed) lines.push(`- **${c.label}** — ${c.detail}`);
      lines.push("");
    }
    if (skipped.length) {
      lines.push("Checks that were **skipped, not passed**:");
      lines.push("");
      for (const c of skipped) lines.push(`- **${c.label}** — ${c.detail}`);
      lines.push("");
    }
  } else {
    lines.push("No quality report was produced for this version.");
    lines.push("");
  }
  if (!input.visualQaAvailable) {
    lines.push(
      "No screenshots were taken. Lead → Launch does not bundle a headless browser, so rendered spacing, overflow and visual hierarchy are **unverified** — look at the site on a real phone before showing it to anyone.",
    );
  }

  h("Known assumptions");
  lines.push(
    "- The copy is written to be defensible, not maximal: no superlatives that cannot be evidenced.",
  );
  lines.push("- Colours and type follow the brief's direction, not a brand guide from the client.");
  lines.push(
    "- Contact actions link to the phone number and email on record. Confirm both before launch.",
  );
  lines.push("- No analytics, consent banner or tracking is included. Add them deliberately if wanted.");

  h("Generated by");
  lines.push(`- Lead → Launch, project \`${input.slug}\`, version ${input.version}`);
  lines.push(`- ${input.builtAt.toISOString()}`);
  lines.push(`- ${input.provider} / ${input.model} (${STRATEGY_META[input.strategy].label})`);
  lines.push("");
  lines.push(
    "This site was reviewed by software. It has not been reviewed by a person until you do it.",
  );
  lines.push("");

  return lines.join("\n");
}

/* --------------------------------------------------------------- artifacts */

/**
 * Writes every file of a version to the artifact store.
 *
 * Text files are kept inline in the row, which is the right call for a static
 * site of a few dozen kilobytes: it makes a version atomically restorable from
 * the database alone, with no second system that can be out of sync. Anything
 * larger goes to the storage provider and the row keeps the key.
 */
const INLINE_LIMIT = 256 * 1024;

export async function persistArtifacts(
  versionId: string,
  slug: string,
  version: number,
  files: PackagedFile[],
): Promise<{ stored: number; bytes: number; durable: boolean }> {
  const storage = getStorageProvider();
  let bytes = 0;

  await prisma.websiteArtifact.deleteMany({ where: { versionId } });

  for (const file of files) {
    const buffer = Buffer.from(file.content, "utf8");
    bytes += buffer.byteLength;
    const inline = buffer.byteLength <= INLINE_LIMIT;
    const key = `${slug}/v${version}/${file.path}`;

    if (!inline) await storage.put(key, buffer, contentTypeFor(file.path));

    await prisma.websiteArtifact.create({
      data: {
        versionId,
        path: file.path,
        bytes: buffer.byteLength,
        contentType: contentTypeFor(file.path),
        sha256: sha256(buffer),
        storageProvider: inline ? "inline" : storage.id,
        storageKey: inline ? null : key,
        content: inline ? file.content : null,
      },
    });
  }

  return { stored: files.length, bytes, durable: storage.durable };
}

export async function readArtifacts(versionId: string): Promise<PackagedFile[]> {
  const rows = await prisma.websiteArtifact.findMany({
    where: { versionId },
    orderBy: { path: "asc" },
  });
  const storage = getStorageProvider();
  const files: PackagedFile[] = [];

  for (const row of rows) {
    if (row.storageProvider === "inline") {
      files.push({ path: row.path, content: row.content ?? "" });
      continue;
    }
    const body = row.storageKey ? await storage.get(row.storageKey) : null;
    if (!body) {
      throw new AppError({
        kind: "not-found",
        message: `"${row.path}" is recorded for this version but is not in ${storage.label}.`,
        remedy: storage.durable
          ? "Check the storage bucket, then rebuild this version."
          : "Local storage is not durable — this build did not survive a restart. Rebuild it.",
      });
    }
    files.push({ path: row.path, content: body.toString("utf8") });
  }

  return files;
}

/* --------------------------------------------------------------------- zip */

export async function packageVersion(
  workspaceId: string,
  versionId: string,
): Promise<{ filename: string; zip: Buffer; files: number }> {
  const version = await prisma.websiteVersion.findFirst({
    where: { id: versionId, project: { workspaceId } },
    include: { project: { include: { prospect: { include: { business: true } } } } },
  });
  if (!version) {
    throw new AppError({
      kind: "not-found",
      message: "Version not found.",
      remedy: "Refresh the Website Studio.",
    });
  }

  const files = await readArtifacts(versionId);
  if (files.length === 0) {
    throw new AppError({
      kind: "not-found",
      message: `Version ${version.version} has no stored files.`,
      remedy:
        "It predates artifact storage, or the build failed before packaging. Run a new build to produce a downloadable version.",
    });
  }

  const entries: ZipEntry[] = files.map((f) => ({ path: f.path, content: f.content }));
  if (version.readmeText && !files.some((f) => f.path.toLowerCase() === "readme.md")) {
    entries.push({ path: "README.md", content: version.readmeText });
  }

  const base = safeFilename(
    `${version.project.prospect.business.name}-v${version.version}`,
    version.project.slug,
  );
  return {
    filename: `${base}.zip`,
    zip: createZip(entries, version.createdAt),
    files: entries.length,
  };
}

/** The file list shown in the Studio, without pulling every byte into memory. */
export async function listVersionFiles(workspaceId: string, versionId: string) {
  const rows = await prisma.websiteArtifact.findMany({
    where: { versionId, version: { project: { workspaceId } } },
    select: { path: true, bytes: true, contentType: true, sha256: true },
    orderBy: { path: "asc" },
  });
  return rows;
}

export function briefOf(project: { briefJson: string | null }): WebsiteBrief | null {
  return fromJson<WebsiteBrief | null>(project.briefJson, null);
}
